/**
 * The export plan behind `sloodge-export.pptx` — the fixture produced by sloodge's *own* M4.3
 * export path (`writeDeckPptx`, and therefore pptxgenjs behind the `SafePptxDeck` boundary).
 *
 * Kept beside the fixture it generates so the committed binary is reproducible and reviewable: a
 * reader can see exactly what is in that file without unzipping it. `tests/unit/export/
 * pptx-fixture-generate.test.ts` is the (skipped) button that rewrites the bytes.
 *
 * This is the *self-consistent* half of the fixture set — the dialect sloodge itself emits, which
 * is the round trip a user is most likely to perform. The independent half is
 * `python-pptx-deck.pptx`, built on a template authored by PowerPoint and therefore carrying real
 * masters, eleven layouts, a theme, placeholder shapes with no explicit geometry, a thumbnail JPEG
 * and a printer-settings blob — none of which this path ever produces. Testing the importer only
 * against our own output would let the importer and the exporter agree on a shared misreading of
 * the format and call it a passing test.
 */

import type { DeckPptxPlan } from '../../../src/shared/export/pptx/types'

/** A deliberately small deck: two structured slides with text, shapes and speaker notes. */
export const SLOODGE_FIXTURE_PLAN: DeckPptxPlan = {
  title: 'Sloodge export fixture',
  author: 'Sloodge',
  slides: [
    {
      tier: 'structured',
      confidence: 100,
      reasons: [],
      notes: 'Opening slide of the round-trip fixture.',
      background: { color: 'FFFFFF' },
      shapes: [
        {
          kind: 'text',
          box: { x: 0.5, y: 0.6, w: 12.33, h: 1.4 },
          align: 'left',
          valign: 'middle',
          runs: [{ text: 'Round-trip fixture', bold: true, fontSize: 40, color: '111827' }],
        },
        {
          kind: 'text',
          box: { x: 0.5, y: 2.1, w: 12.33, h: 0.9 },
          align: 'left',
          valign: 'top',
          runs: [{ text: 'Generated by sloodge M4.3', fontSize: 20, color: '4B5563' }],
        },
        {
          kind: 'roundRect',
          box: { x: 0.5, y: 3.4, w: 3.2, h: 1.6 },
          fill: { color: '4C8DFF' },
          rectRadius: 0.12,
        },
      ],
    },
    {
      tier: 'structured',
      confidence: 100,
      reasons: [],
      notes: '',
      background: { color: 'F8FAFC' },
      shapes: [
        {
          kind: 'text',
          box: { x: 0.5, y: 0.6, w: 12.33, h: 1.1 },
          align: 'left',
          valign: 'middle',
          runs: [{ text: 'Second slide', bold: true, fontSize: 32, color: '111827' }],
        },
        {
          kind: 'text',
          box: { x: 0.5, y: 1.9, w: 12.33, h: 3.0 },
          align: 'left',
          valign: 'top',
          runs: [
            { text: 'First bullet', fontSize: 20, bullet: true, color: '111827' },
            { text: 'Second bullet', fontSize: 20, bullet: true, color: '111827' },
            { text: 'Third bullet', fontSize: 20, bullet: true, color: '111827' },
          ],
        },
        {
          kind: 'ellipse',
          box: { x: 9.5, y: 3.2, w: 2.2, h: 2.2 },
          fill: { color: 'F59E0B' },
          line: { color: '92400E', width: 2 },
        },
      ],
    },
  ],
}
